name: Deployment on Main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.11.7]

    steps:
      - uses: actions/checkout@v2
      - name: Django aws eb deployment
        uses: joel-hanson/django-aws-eb-deploy@V1.1
        with:
          python_version: ${{ matrix.python_version }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          django_path: .
          deploy: true
          min_coverage: 10

      - name: Coverage report artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage report
          path: output/coverage_report.txt

      - name: Coverage report artifacts if failed
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: coverage report if failed
          path: output/coverage_report.txt

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: bandit
          path: output/security_report.txt
